FROM python:3.10-slim

# 1) Ajustes de locale caso use datas/valores
RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    && rm -rf /var/lib/apt/lists/*

# 2) Diretório de trabalho
WORKDIR /app

# 3) Copia e instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4) Copia o código
COPY . .

# 5) Entry point
CMD ["python", "main.py"]